name: download_data
channels:
  - conda-forge
  - defaults
dependencies:
  - python=3.11
  - jupyterlab=4.1.3
  - seaborn=0.13.2
  - pandas=2.2.1
  - pip=23.3.1
  - ipython=8.12.2
  - ydata-profiling=4.10.0
  - pyarrow=14.0.2
  - ipywidgets=8.1.2
  - pip:
      - wandb==0.16.4