_wandb:
    value:
        cli_version: 0.21.0
        e:
            xhlbz6k8lk3bag01frk9jv6opykb1qqr:
                args:
                    - artifact
                    - put
                    - --name
                    - exercise_4/genres_mod.parquet
                    - --type
                    - raw_data
                    - --description
                    - A modified version of the songs dataset
                    - genres_mod.parquet
                cpu_count: 12
                cpu_count_logical: 24
                cudaVersion: "12.9"
                disk:
                    /:
                        total: "1081101176832"
                        used: "26392272896"
                email: pjacob7@wgu.edu
                executable: /home/baelfur/miniconda3/envs/udacity/bin/python3.8
                git:
                    commit: 922f112971ba6f97302ee14a067eb154424ace5a
                    remote: https://github.com/Baelfur/nd0821-c2-build-model-workflow-exercises.git
                gpu: NVIDIA GeForce RTX 5070 Ti
                gpu_count: 1
                gpu_nvidia:
                    - architecture: Blackwell
                      memoryTotal: "17094934528"
                      name: NVIDIA GeForce RTX 5070 Ti
                      uuid: GPU-294f49f4-16b5-c3e4-6622-cb0666052085
                host: beast
                memory:
                    total: "33610530816"
                os: Linux-5.15.167.4-microsoft-standard-WSL2-x86_64-with-glibc2.17
                program: /home/baelfur/miniconda3/envs/udacity/bin/wandb
                python: CPython 3.8.20
                root: /home/baelfur/nd0821-c2-build-model-workflow-exercises/lesson-2-data-exploration-and-preparation/exercises/exercise_4/starter
                startedAt: "2025-07-13T05:46:23.922640Z"
                writerId: xhlbz6k8lk3bag01frk9jv6opykb1qqr
        m: []
        python_version: 3.8.20
        t:
            "3":
                - 2
                - 16
            "4": 3.8.20
            "5": 0.21.0
            "12": 0.21.0
            "13": linux-x86_64
path:
    value: genres_mod.parquet
