wandb_version: 1

_wandb:
  desc: null
  value:
    python_version: 3.12.11
    cli_version: 0.16.4
    is_jupyter_run: true
    is_kaggle_kernel: false
    start_time: 1752386166.0
    t:
      1:
      - 55
      2:
      - 55
      3:
      - 2
      - 23
      4: 3.12.11
      5: 0.16.4
      8:
      - 1
      - 5
      13: linux-x86_64
    session_history: code/_session_history.ipynb
